# ----------- ENVIRONMENT VARIABLES -----------
x-backend_env_variables: &backend_env_variables
  ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
  FRONTEND_HOST: ${FRONTEND_HOST}
  FLASK_APP: app.py
  FLASK_ENV: prod
  FLASK_RUN_PORT: ${BACKEND_PORT_FLASK}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  MONGO_INITDB_DATABASE: archihub-${ENVIRONMENT_NAME}
  MONGO_DATABASE: archihub-${ENVIRONMENT_NAME}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CELERY_BROKER_HOST: ${CELERY_BROKER_HOST}
  FLASK_DEBUG: ${FLASK_DEBUG}
  USER_FILES_PATH: ${USER_FILES_PATH}
  WEB_FILES_PATH: ${WEB_FILES_PATH}
  ORIGINAL_FILES_PATH: ${ORIGINAL_FILES_PATH}
  TEMPORAL_FILES_PATH: ${TEMPORAL_FILES_PATH}
  MONGO_IP_SERVER: ${MONGO_HOST}
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: '27017'
  ELASTIC_DOMAIN: ${ELASTIC_DOMAIN}
  ELASTIC_USER: ${ELASTIC_USER}
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  ELASTIC_PORT: ${ELASTIC_PORT}
  ELASTIC_INDEX_PREFIX: archihub-${ENVIRONMENT_NAME}
  HF_TOKEN: ${HF_TOKEN}
# --------------------------------------------
x-worker_env_variables: &worker_env_variables
  ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
  FRONTEND_HOST: ${FRONTEND_HOST}
  FLASK_APP: app.py
  FLASK_ENV: prod
  FLASK_RUN_PORT: ${BACKEND_PORT_FLASK}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  MONGO_INITDB_DATABASE: archihub-${ENVIRONMENT_NAME}
  MONGO_DATABASE: archihub-${ENVIRONMENT_NAME}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CELERY_BROKER_HOST: ${CELERY_BROKER_HOST}
  FLASK_DEBUG: ${FLASK_DEBUG}
  USER_FILES_PATH: ${USER_FILES_PATH}
  WEB_FILES_PATH: ${WEB_FILES_PATH}
  ORIGINAL_FILES_PATH: ${ORIGINAL_FILES_PATH}
  TEMPORAL_FILES_PATH: ${TEMPORAL_FILES_PATH}
  MONGO_IP_SERVER: ${MONGO_HOST}
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: '27017'
  CELERY_WORKER: true
  ELASTIC_DOMAIN: ${ELASTIC_DOMAIN}
  ELASTIC_USER: ${ELASTIC_USER}
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  ELASTIC_PORT: ${ELASTIC_PORT}
  ELASTIC_INDEX_PREFIX: archihub-${ENVIRONMENT_NAME}
  HF_TOKEN: ${HF_TOKEN}
# --------------------------------------------
x-mongo_db_env_variables: &mongo_db_env_variables
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  MONGO_INITDB_DATABASE: archihub-${ENVIRONMENT_NAME}
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: '27017'

services:

# ------------------------- ARCHIHUB FLASK BACKEND -------------------
  archihub_flask_backend:
    build:
      context: ./backend
      args:
        - PORT=${BACKEND_PORT_FLASK}
    ports:
      - ${BACKEND_PORT_FLASK}:${BACKEND_PORT_FLASK}
    environment:
      <<: *backend_env_variables
    volumes:
      - ./stash/elastic_certs:/stash/elastic_certs:ro
      - ./stash/wait_for:/wait_for:ro
      - ${USERFILES_PATH}:/app/userfiles
      - ${WEBFILE_PATH}:/app/webfiles
      - ${UPLOAD_PATH}:/app/uploads
      - ${TEMPORAL_PATH}:/app/temporal
    depends_on:
      - redis
    command: ["/bin/bash","/app/start.sh"]

# ----------------------- CELERY WORKER SERVICE -----------------------
  celery_worker:
    build:
      context: ./backend
      args:
        - PORT=${BACKEND_PORT_FLASK}
    environment:
      <<: *worker_env_variables
    volumes:
      - ${USERFILES_PATH}:/app/userfiles
      - ${WEBFILE_PATH}:/app/webfiles
      - ${UPLOAD_PATH}:/app/uploads
      - ${TEMPORAL_PATH}:/app/temporal
    depends_on:
      - archihub_flask_backend
      - redis
    working_dir: /app
    command: 'celery --app app.celery_app worker --loglevel INFO'

# ---------------------- FRONT END SERVICE ----------------------
  archihub_frontend:
    build:
      context: ./frontend
      args:
        - FLASK_PORT=${BACKEND_PORT_FLASK}
    environment:
      - FLASK_PORT=${BACKEND_PORT_FLASK}
    ports:
      - "80:80"
    depends_on:
      - archihub_flask_backend

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"